version: "3.9"
   
services:

  
  django_test:
    build: .
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    #command: ls -la
    volumes:
      - ./django_test:/code
    ports:
      - "8002:8002"
    